stages:
  - test

variables:
  DEBUG: "1"

.pytest:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME == "test"
      when: always
    - when: manual
  tags:
    - qubes
  artifacts:
    when: always
    paths:
      - results
  before_script:
    - sudo dnf install -y python3-pathspec sequoia-sqv python3-pytest
  after_script:
    - mkdir $CI_PROJECT_DIR/results
    - cp -r ~/pytest-of-user/pytest-current/github-current/*.log $CI_PROJECT_DIR/results || true
    - cp -r ~/pytest-of-user/pytest-current/github-current/builder-github-logs $CI_PROJECT_DIR/results/


test_action:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_action.py

test_command:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_command.py

test_rpc:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_rpc.py

test_notify:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_notify.py

mypy:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME == "test"
      when: always
    - when: manual
  image: fedora:latest
  tags:
    - docker
  before_script:
    - sudo dnf install -y python3-mypy python3-pip python3-pathspec git
    - sudo python3 -m pip install types-PyYAML types-python-dateutil
    - git clone -b main https://github.com/QubesOS/qubes-builderv2
  script:
    - PYTHONPATH="$PWD/qubes-builderv2" MYPYPATH="$PWD/qubes-builderv2" mypy --install-types --non-interactive --junit-xml mypy.xml
  artifacts:
    reports:
      junit: mypy.xml
